server:
  address: 0.0.0.0
  port: ${PORT:8080}

base-url: /api

spring:
  application:
    name: taskManager

  profiles:
    active: ${APP_ENV:development}

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  output:
    ansi:
      enabled: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://a1f4f0db3ae5b97e63ecbd9f2e197748@o4506367904120832.ingest.sentry.io/4506367910215680
  traces-sample-rate: 1.0

