server:
  address: 0.0.0.0
  port: ${PORT:8080}

base-url: /api

spring:
  application:
    name: taskManager

  profiles:
    active: ${APP_ENV:development}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  output:
    ansi:
      enabled: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

